### ISSUE TITLE
train.py的错误

### ISSUE THREAD

**Issue by dongda-villager** [Ninzore/Chinese_Chatbot_Torch#3]
老哥还对代码做维护吗，train.py这个load报错怎么解决
![image](https://user-images.githubusercontent.com/83150925/211829970-1c0ee48f-f3c5-4441-ac8c-060592032485.png)

**Comment by Ninzore** [comment]
不维护了，这套代码太旧了。这个地方如果没有checkpoints的话把if删了就行。

**Comment by dongda-villager** [comment]
好的，谢谢大佬
